#!/bin/bash

NC=`which nc`
LOCALSTATEDIR=`icinga2 variable get LocalStateDir`
LIVESTATUSSOCKET="$LOCALSTATEDIR/run/icinga2/cmd/livestatus"
LIVESTATUSHOST="127.0.0.1"
LIVESTATUSPORT="6558"
LIVESTATUSQUERIES="./queries"

LIVESTATUSTABLE=$1

echo -e "Querying Livestatus socket: $LIVESTATUSSOCKET"

if [ -n "$LIVESTATUSTABLE" ]; then
	cat "$LIVESTATUSTABLE"
	(cat "$LIVESTATUSTABLE"; sleep 1) | $NC -U $LIVESTATUSSOCKET
else

	echo -e "Looking into $LIVESTATUSQUERIES\n"
	for q in $(find $LIVESTATUSQUERIES -type f)
	do
		cat $q
		(cat $q; sleep 1) | $NC -U $LIVESTATUSSOCKET
		echo -e "================================\n\n"
	done
fi
