.TH ICINGA2 "15" "June 2014" "icinga2 - The Icinga 2 network monitoring daemon." "System Administration Utilities"

.SH NAME
icinga2-prepare-dirs \- Prepare directories and their permissions for use by Icinga 2.

.SH DESCRIPTION
This script is used internally by the initscripts of Icinga 2 to prepare
prepare directories and their permissions. This script is not intended to be called by users.

.SH OPTIONS
.TP
\fB<sysconfig file>\fR
Absolute path to the sysconfig file of Icinga 2.

.SH AUTHOR
Icinga2 is maintained by the Icinga Project <info@icinga.org>.

.SH "REPORTING BUGS"
Report bugs at <https://dev.icinga.org/>
.br
Icinga home page: <http://www.icinga.org/>

.SH COPYRIGHT
Copyright \(co 2012\-2014 Icinga Development Team (http://www.icinga.org)
License GPLv2+: GNU GPL version 2 or later <http://gnu.org/licenses/gpl2.html>
.br
This is free software: you are free to change and redistribute it.
There is NO WARRANTY, to the extent permitted by law.
