.TH ICINGA2 "8" "June 2014" "icinga2 - The Icinga 2 network monitoring daemon." "System Administration Utilities"

.SH NAME
icinga2-enable-feature \- Enable Icinga 2 features.

.SH DESCRIPTION
icinga2-enable-feature \- Enable Icinga 2 features.

.SH OPTIONS
.TP
\fB<features>\fR
Whitespace separated list of Icinga 2 features to be enabled

.SH FILES
.TP
.IP /etc/icinga2/features-available
Configuration directory for available Icinga2 features

.SH AUTHOR
Icinga2 is maintained by the Icinga Project <info@icinga.org>.

.SH "REPORTING BUGS"
Report bugs at <https://dev.icinga.org/>
.br
Icinga home page: <http://www.icinga.org/>

.SH COPYRIGHT
Copyright \(co 2012\-2014 Icinga Development Team (http://www.icinga.org)
License GPLv2+: GNU GPL version 2 or later <http://gnu.org/licenses/gpl2.html>
.br
This is free software: you are free to change and redistribute it.
There is NO WARRANTY, to the extent permitted by law.
