#!/bin/sh

set -e

if [ -f /usr/share/debconf/confmodule ]; then
        . /usr/share/debconf/confmodule
fi

if [ -f /usr/share/dbconfig-common/dpkg/postrm ]; then
        . /usr/share/dbconfig-common/dpkg/postrm
        dbc_go icinga2-ido-mysql $@
fi

if [ "$1" = "purge" ]; then
    rm -f /etc/icinga2/features-available/ido-mysql.conf
    rm -f /etc/icinga2/features-enabled/ido-mysql.conf
    if which ucf >/dev/null; then
        ucf --purge /etc/icinga2/features-available/ido-mysql.conf 
    fi
    db_purge
fi

#DEBHELPER#

