debian/tmp/etc/icinga2
debian/config/apt.conf        etc/icinga2/conf.d/hosts/localhost
debian/config/kernel.conf     etc/icinga2/conf.d/hosts/localhost
debian/config/check_kernel    etc/sudoers.d
usr/bin/icinga2-build*
usr/bin/icinga2-sign-key
usr/sbin/icinga2-*-feature
usr/sbin/icinga2-setup-agent
usr/sbin/icinga2-discover-agent
usr/sbin/icinga2-forget-agent
usr/sbin/icinga2-list-agents
usr/share/icinga2
