/* Icinga 2 | (c) 2012 Icinga GmbH | GPLv2+ */

#include "icinga/service.hpp"
#include "icinga/dependency.hpp"
#include "base/logger.hpp"
#include <unordered_map>
#include <numeric>

using namespace icinga;

// Is the default (dummy) redundancy group used to group non-redundant dependencies.
static String l_DefaultRedundancyGroup(Utility::NewUniqueID());

RedundancyGroup::RedundancyGroup(const String& name, const Dependency::Ptr& dependency): m_Name(name)
{
	AddMember(dependency);
}

/**
 * Check if the provided redundancy group matches the randomly generated (default) one.
 *
 * @param name The redundancy group name you want to check.
 *
 * @return bool - Returns true if the provided redundancy group matches the randomly generated (default) one.
 */
bool RedundancyGroup::IsDefault(const String& name)
{
	return  name == l_DefaultRedundancyGroup;
}

/**
 * Check if the current redundancy group has any members.
 *
 * @return bool - Returns true if the current redundancy group has any members.
 */
bool RedundancyGroup::HasMembers() const
{
	return GetMemberCount() > 0;
}

/**
 * Add a member to the current redundancy group.
 *
 * @param member The dependency to add to the redundancy group.
 */
void RedundancyGroup::AddMember(const Dependency::Ptr& member)
{
	std::lock_guard lock(m_Mutex);
	m_Members.emplace(member);

	if (!IsDefault(GetName())) {
		// We're just going to change the unique name from which the Icinga DB identifier is derived,
		// but let just IcingaDB regenerate and reset it when processing the Dependency object creation.
		auto it (m_UniqueName.emplace(member->GetParent()->GetName(), 1));
		if (!it.second) { // Whether there is already a member with the same parent!
			// YES, it's weird to have two different dependencies with same parent, but it's possible.
			it.first->second += 1;
		}
	}
}

/**
 * Remove a member from the current redundancy group.
 *
 * @param member The dependency to remove from the redundancy group.
 */
void RedundancyGroup::RemoveMember(const Dependency::Ptr& member)
{
	std::lock_guard lock(m_Mutex);
	m_Members.erase(member);

	if (!IsDefault(GetName())) {
		// We're just going to change the unique name from which the Icinga DB identifier is derived,
		// but let just IcingaDB regenerate and reset it when processing the Dependency object deletion.
		if (auto it (m_UniqueName.find(member->GetParent()->GetName())); it != m_UniqueName.end()) {
			it->second -= 1;

			if (it->second == 0) {
				m_UniqueName.erase(it);
			}
		}
	}
}

/**
 * Retrieve a copy of all the members of the current redundancy group.
 *
 * @return - Returns a set of the member of this redundancy group.
 */
std::unordered_set<Dependency::Ptr> RedundancyGroup::GetMembers() const
{
	std::lock_guard lock(m_Mutex);
	return {m_Members.begin(), m_Members.end()};
}

/**
 * Retrieve the number of members in the current redundancy group.
 *
 * This function mainly exists for optimization purposes, i.e. instead of getting a copy of the members and
 * counting them, we can directly query the number of members.
 *
 * @return - Returns the number of members in the current redundancy group.
 */
int RedundancyGroup::GetMemberCount() const
{
	std::lock_guard lock(m_Mutex);
	return m_Members.size();
}

/**
 * Set the Icinga DB identifier for the current redundancy group.
 *
 * The only usage of this function is the Icinga DB feature used to cache the unique hash of this redundancy groups.
 *
 * @param identifier The Icinga DB identifier to set.
 */
void RedundancyGroup::SetIcingaDBIdentifier(const String& identifier)
{
	std::lock_guard lock(m_Mutex);
	m_IcingaDBIdentifier = identifier;
}

/**
 * Retrieve the Icinga DB identifier for the current redundancy group.
 *
 * When the identifier is not already set by Icinga DB via the SetIcingaDBIdentifier method,
 * this will just return an empty string.
 *
 * @return - Returns the Icinga DB identifier for the current redundancy group.
 */
String RedundancyGroup::GetIcingaDBIdentifier() const
{
	std::lock_guard lock(m_Mutex);
	return m_IcingaDBIdentifier;
}

/**
 * Retrieve the (non-unique) name of the current redundancy group.
 *
 * The name of the redundancy group is the same as the one located in the configuration files.
 *
 * @return - Returns the name of the current redundancy group.
 */
const String& RedundancyGroup::GetName() const
{
	// We don't need to lock the mutex here, as the name is set once during
	// the object construction and never changed afterwards.
	return m_Name;
}

/**
 * Retrieve the unique name of the current redundancy group.
 *
 * The unique name is generated by summing up the names of all the parent dependencies of the members.
 * This string should be used to generate a unique deterministic hash for the redundancy group.
 *
 * @return - Returns the unique name of the current redundancy group.
 */
String RedundancyGroup::GetUniqueName() const
{
	std::lock_guard lock(m_Mutex);
	return std::accumulate(
		m_UniqueName.begin(),
		m_UniqueName.end(),
		GetName(), // Start with the redundancy group name
		[](const String& output, const std::pair<String, int>& pair) {
			return output + "!" + pair.first;
		}
	);
}

void Checkable::AddDependency(const Dependency::Ptr& dep)
{
	std::unique_lock<std::mutex> lock(m_DependencyMutex);
	m_Dependencies.insert(dep);
}

void Checkable::RemoveDependency(const Dependency::Ptr& dep)
{
	std::unique_lock<std::mutex> lock(m_DependencyMutex);
	m_Dependencies.erase(dep);
}

std::vector<Dependency::Ptr> Checkable::GetDependencies() const
{
	std::unique_lock<std::mutex> lock(m_DependencyMutex);
	return std::vector<Dependency::Ptr>(m_Dependencies.begin(), m_Dependencies.end());
}

void Checkable::AddReverseDependency(const Dependency::Ptr& dep)
{
	std::unique_lock<std::mutex> lock(m_DependencyMutex);
	m_ReverseDependencies.insert(dep);
}

void Checkable::RemoveReverseDependency(const Dependency::Ptr& dep)
{
	std::unique_lock<std::mutex> lock(m_DependencyMutex);
	m_ReverseDependencies.erase(dep);
}

std::vector<Dependency::Ptr> Checkable::GetReverseDependencies() const
{
	std::unique_lock<std::mutex> lock(m_DependencyMutex);
	return std::vector<Dependency::Ptr>(m_ReverseDependencies.begin(), m_ReverseDependencies.end());
}

bool Checkable::IsReachable(DependencyType dt, Dependency::Ptr *failedDependency, int rstack) const
{
	/* Anything greater than 256 causes recursion bus errors. */
	int limit = 256;

	if (rstack > limit) {
		Log(LogWarning, "Checkable")
			<< "Too many nested dependencies (>" << limit << ") for checkable '" << GetName() << "': Dependency failed.";

		return false;
	}

	for (const Checkable::Ptr& checkable : GetParents()) {
		if (!checkable->IsReachable(dt, failedDependency, rstack + 1))
			return false;
	}

	/* implicit dependency on host if this is a service */
	const auto *service = dynamic_cast<const Service *>(this);
	if (service && (dt == DependencyState || dt == DependencyNotification)) {
		Host::Ptr host = service->GetHost();

		if (host && host->GetState() != HostUp && host->GetStateType() == StateTypeHard) {
			if (failedDependency)
				*failedDependency = nullptr;

			return false;
		}
	}

	auto deps = GetDependencies();

	std::unordered_map<std::string, Dependency::Ptr> violated; // key: redundancy group, value: nullptr if satisfied, violating dependency otherwise

	for (const Dependency::Ptr& dep : deps) {
		std::string redundancy_group = dep->GetRedundancyGroup();

		if (!dep->IsAvailable(dt)) {
			if (redundancy_group.empty()) {
				Log(LogDebug, "Checkable")
					<< "Non-redundant dependency '" << dep->GetName() << "' failed for checkable '" << GetName() << "': Marking as unreachable.";

				if (failedDependency)
					*failedDependency = dep;

				return false;
			}

			// tentatively mark this dependency group as failed unless it is already marked;
			//  so it either passed before (don't overwrite) or already failed (so don't care)
			// note that std::unordered_map::insert() will not overwrite an existing entry
			violated.insert(std::make_pair(redundancy_group, dep));
		} else if (!redundancy_group.empty()) {
			violated[redundancy_group] = nullptr;
		}
	}

	auto violator = std::find_if(violated.begin(), violated.end(), [](auto& v) { return v.second != nullptr; });
	if (violator != violated.end()) {
		Log(LogDebug, "Checkable")
			<< "All dependencies in redundancy group '" << violator->first << "' have failed for checkable '" << GetName() << "': Marking as unreachable.";

		if (failedDependency)
			*failedDependency = violator->second;

		return false;
	}

	if (failedDependency)
		*failedDependency = nullptr;

	return true;
}

/**
 * Checks whether the last check result of this Checkable affects its child dependencies.
 *
 * @return bool - Returns true if the Checkable affects its child dependencies, otherwise false.
 */
bool Checkable::AffectsChildren() const
{
	auto cr(GetLastCheckResult());
	if (!cr || IsStateOK(cr->GetState()) || !IsReachable()) {
		// If there is no check result, the state is OK, or the Checkable is not reachable, we can't
		// safely determine whether the Checkable affects its child dependencies.
		return false;
	}

	for (auto& dep: GetReverseDependencies()) {
		if (!dep->IsAvailable(DependencyState)) {
			// If one of the child dependency is not available, then it's definitely due to the
			// current Checkable state, so we don't need to verify the remaining ones.
			return true;
		}
	}

	return false;
}

std::set<Checkable::Ptr> Checkable::GetParents() const
{
	std::set<Checkable::Ptr> parents;

	for (const Dependency::Ptr& dep : GetDependencies()) {
		Checkable::Ptr parent = dep->GetParent();

		if (parent && parent.get() != this)
			parents.insert(parent);
	}

	return parents;
}

std::set<Checkable::Ptr> Checkable::GetChildren() const
{
	std::set<Checkable::Ptr> parents;

	for (const Dependency::Ptr& dep : GetReverseDependencies()) {
		Checkable::Ptr service = dep->GetChild();

		if (service && service.get() != this)
			parents.insert(service);
	}

	return parents;
}

/**
 * Retrieve the total number of all the children of the current Checkable.
 *
 * Note, this function performs a recursive call chain traversing all the children of the current Checkable
 * up to a certain limit (256). When that limit is reached, it will log a warning message and abort the operation.
 * Thus, the returned number may not reflect the actual total number of children involved in the dependency chain.
 *
 * In fact, there is already a method GetAllChildren() that does kind of same thing, but it involves too much
 * overhead, copying and passing around sets, which is not necessary for this simple operation (just count them).
 *
 * @return int - Returns the total number of all the children of the current Checkable.
 */
int Checkable::GetAllChildrenCount(int rstack) const
{
	if (rstack > 256) {
		Log(LogWarning, "Checkable")
			<< "Too many nested dependencies (>" << 256 << ") for checkable '" << GetName() << "': aborting count.";

		// The limit from GetAllChildrenInternal() doesn't seem to make sense, and appears to be
		// some random number. So, this limit is set to 256 to match the limit in IsReachable().
		return 0;
	}

	int count = 0;
	// Actually, incrementing the rstack should be done once outside the loop here, but since IsReachable()
	// applies the limit the exact same way, it should be fine to limit the sum of calls to 256 here as well.
	for (auto& dependency: GetReverseDependencies()) {
		count += dependency->GetChild()->GetAllChildrenCount(rstack + 1) + 1;
	}

	return count;
}

std::set<Checkable::Ptr> Checkable::GetAllChildren() const
{
	std::set<Checkable::Ptr> children = GetChildren();

	GetAllChildrenInternal(children, 0);

	return children;
}

void Checkable::GetAllChildrenInternal(std::set<Checkable::Ptr>& children, int level) const
{
	if (level > 32)
		return;

	std::set<Checkable::Ptr> localChildren;

	for (const Checkable::Ptr& checkable : children) {
		std::set<Checkable::Ptr> cChildren = checkable->GetChildren();

		if (!cChildren.empty()) {
			GetAllChildrenInternal(cChildren, level + 1);
			localChildren.insert(cChildren.begin(), cChildren.end());
		}

		localChildren.insert(checkable);
	}

	children.insert(localChildren.begin(), localChildren.end());
}
