name: Linux

on:
  push: {}
  pull_request: {}

concurrency:
  group: linux-${{ github.event_name == 'push' && github.sha || github.ref }}
  cancel-in-progress: true

jobs:
  linux:
    name: ${{ matrix.distro }}${{ matrix.platform != 'linux/amd64' && format(' ({0})', matrix.platform) || '' }}
    runs-on: ubuntu-latest

    strategy:
      fail-fast: false
      max-parallel: 2
      matrix:
        distro:
          - amazonlinux:2
        platform:
          - linux/amd64

    steps:
      - name: Checkout HEAD
        uses: actions/checkout@v6

      - name: Turn on Problem Matcher
        run: echo "::add-matcher::.github/problem-matchers/gcc.json"

      - name: Restore/backup ccache
        uses: actions/cache@v5
        with:
          path: ccache
          key: ccache/${{ matrix.distro }}

      - name: Build Alpine Docker Image
        if: "matrix.distro == 'alpine:bash'"
        run: >-
          docker build --file .github/workflows/alpine-bash.Dockerfile
          --tag alpine:bash `mktemp -d`

      - name: Build Icinga
        run: >-
          docker run --rm -v "$(pwd):/icinga2" -e DISTRO=${{ matrix.distro }}
          --platform ${{ matrix.platform }} ${{ matrix.distro }} /icinga2/.github/workflows/linux.bash
