#This is the default environment Icinga 2 runs with.
#Make your changes here.

#DAEMON=@CMAKE_INSTALL_FULL_SBINDIR@/icinga2
#ICINGA2_CONFIG_FILE=@ICINGA2_CONFIGDIR@/icinga2.conf
#ICINGA2_INIT_RUN_DIR=@ICINGA2_INITRUNDIR@
#ICINGA2_PID_FILE=@ICINGA2_INITRUNDIR@/icinga2.pid
#ICINGA2_LOG_DIR=@ICINGA2_LOGDIR@
#ICINGA2_ERROR_LOG=@ICINGA2_LOGDIR@/error.log
#ICINGA2_STARTUP_LOG=@ICINGA2_LOGDIR@/startup.log
#ICINGA2_LOG=@ICINGA2_LOGDIR@/icinga2.log
#ICINGA2_CACHE_DIR=@ICINGA2_CACHEDIR@
#ICINGA2_USER=@ICINGA2_USER@
#ICINGA2_GROUP=@ICINGA2_GROUP@
#ICINGA2_COMMAND_GROUP=@ICINGA2_COMMAND_GROUP@
